apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: hsrn-netbox
  name: replication-media-cloned
  annotations:
    cephbackup.hpc.nyu.edu/backup: "false"
spec:
  volumeMode: Filesystem
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: csi-rbd-3-sc
  dataSource:
    kind: PersistentVolumeClaim
    name: hsrn-netbox-media
