apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: hsrn-netbox
  name: replication-postgresql-cloned
  annotations:
    cephbackup.hpc.nyu.edu/backup: "false"
spec:
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 8Gi
  storageClassName: csi-rbd-3-sc
  dataSource:
    kind: PersistentVolumeClaim
    name: data-hsrn-netbox-postgresql-0
