apiVersion: batch/v1
kind: Job
metadata:
  namespace: hsrn-netbox
  name: replication
spec:
  activeDeadlineSeconds: 3600
  backoffLimit: 3
  template:
    spec:
      restartPolicy: Never
      containers:
        - name: replication
          image: quay.io/remram44/networking:20250306
          imagePullPolicy: IfNotPresent
          args:
            - "sh"
            - "-c"
            - |
              set -eu

              mkdir /root/.ssh
              printf '%s\n' "$HOST_KEY" > /root/.ssh/known_hosts

              ssh -i /var/run/secrets/replication/upload-key netbox-upload@${TARGET} rm -f /netbox/replicated/ready

              rsync -e 'ssh -i /var/run/secrets/replication/upload-key' -az /postgresql/data/ netbox-upload@${TARGET}:/netbox/replicated/postgresql/data

              rsync -e 'ssh -i /var/run/secrets/replication/upload-key' -az /media/devicetype-images /media/image-attachments netbox-upload@${TARGET}:/netbox/replicated/media/

              ssh -i /var/run/secrets/replication/upload-key netbox-upload@${TARGET} touch /netbox/replicated/ready
          env:
            - name: TARGET
              value: "10.144.64.227"
            - name: HOST_KEY
              value: "10.144.64.227 ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIL56p9h1LtsjTK+RdcrhnOjgbUfTdANf74+nhozAtGNh"
          volumeMounts:
            - mountPath: /postgresql
              name: postgresql
            - mountPath: /media
              name: media
            - mountPath: /var/run/secrets/replication
              name: secret
      volumes:
        - name: postgresql
          persistentVolumeClaim:
            claimName: replication-postgresql-cloned
        - name: media
          persistentVolumeClaim:
            claimName: replication-media-cloned
        - name: secret
          secret:
            secretName: replication
            defaultMode: 448 # 0o700
